// 11c: dashboard figures and to-do links on company home; grouped home buttons.
import { launch, createCompany, shot, check, done, post } from '../lib.mjs'

const { app, page, errors } = await launch({ fresh: true })
await createCompany(page)
await post(page, '2026-02-01', 'Sale', [['1000', 50000], ['4000', -50000]])
await post(page, '2026-03-01', 'Materials on card', [['5000', 12000], ['2100', -12000]])
await page.reload()
await page.waitForSelector('.dashboard')
const figures = await page.locator('.figures').innerText()
check(/Sales 2026 so far\s*\$500\.00/.test(figures), 'sales so far 500.00')
check(/Net income\s*\$380\.00/.test(figures), 'net income 380.00')
check(/Cash\s*\$500\.00/.test(figures), 'cash 500.00')
check(/You owe\s*\$120\.00/.test(figures), 'you owe 120.00 (card)')
const groups = await page.locator('.home-groups').innerText()
check(['ENTER', 'BRING IN', 'SELL AND MAKE', 'YEAR END'].every((g) => groups.toUpperCase().includes(g)), 'home buttons grouped')
await shot(page, 'dashboard')
await page.locator('.todo').getByRole('button', { name: /Reconcile Checking account/ }).click()
await page.getByRole('heading', { name: 'Reconcile' }).waitFor()
check(true, 'to-do link opens Reconcile')
await page.getByRole('button', { name: 'Close' }).first().click()
await page.getByRole('button', { name: 'Details' }).click()
check((await page.locator('.details').innerText()).includes('Company folder'), 'company details on request')
await app.close()
done(errors)
