// 9c: contractors and 1099-NEC list, fixed assets, mileage, home office.
import { launch, createCompany, shot, check, done, post } from '../lib.mjs'

const { app, page, errors } = await launch({ fresh: true })
await createCompany(page)
await post(page, '2026-02-01', 'Ana Polishing Feb', [['6200', 150000], ['1000', -150000]])
await post(page, '2026-03-01', 'Ana Polishing Mar', [['6200', 80000], ['1000', -80000]])
await post(page, '2026-03-05', 'Photo Bob', [['6200', 50000], ['2100', -50000]])
await post(page, '2026-04-01', 'Rolling mill', [['1500', 120000], ['1000', -120000]])
await page.reload()
await page.waitForSelector('.app-main h1')

await page.getByRole('button', { name: 'Year-end records' }).click()
await page.getByRole('heading', { name: 'Year-end records' }).waitFor()
await page.getByLabel('Records year').selectOption('2026')
await page.getByLabel('Contractor name').fill('Ana Polishing')
await page.getByLabel('Contractor tax ID last four').fill('1234')
await page.getByLabel(/I have their W-9/).check()
await page.getByRole('button', { name: 'Add contractor' }).click()
await page.getByText('Contractor added.').waitFor()
await page.getByLabel('Contractor name').fill('Photo Bob')
await page.getByRole('button', { name: 'Add contractor' }).click()
await page.locator('.nec-table').waitFor()
const nec = await page.locator('.nec-table').innerText()
check(/Ana Polishing[^\n]*\$2,300\.00[^\n]*Yes/.test(nec), 'Ana: $2,300 by bank, needs a 1099-NEC')
check(/Photo Bob[^\n]*\$0\.00[^\n]*\$500\.00[^\n]*No/.test(nec), 'Photo Bob: card payment left out')
await shot(page, 'records-nec')

await page.locator('.records .tabs').getByRole('button', { name: 'Fixed assets' }).click()
await page.getByLabel('Asset name').fill('Rolling mill')
await page.getByLabel('Asset cost').fill('1200')
await page.getByLabel('Asset in service').fill('2026-04-01')
await page.getByRole('button', { name: 'Add asset' }).click()
await page.getByText('Asset added.').waitFor()
check((await page.locator('.records-tab').innerText()).includes('Fixed-asset accounts in your books on 2026-12-31: $1,200.00'), 'assets tie to the books')

await page.locator('.records .tabs').getByRole('button', { name: 'Mileage' }).click()
await page.getByLabel('Trip date').fill('2026-02-10')
await page.getByLabel('Trip miles').fill('12.5')
await page.getByLabel('Trip purpose').fill('Post office shipping')
await page.getByRole('button', { name: 'Add trip' }).click()
await page.getByText('Trip added.').waitFor()
await page.getByLabel('Mileage rate').fill('70')
await page.getByRole('button', { name: 'Save rate' }).click()
await page.getByText('Rate saved.').waitFor()
check((await page.locator('.mileage-total').innerText()).includes('12.5 business miles × 70.0¢ = $8.75'), 'mileage 12.5 × 70¢ = $8.75')

await page.locator('.records .tabs').getByRole('button', { name: 'Home office' }).click()
await page.getByLabel('Office square feet').fill('150')
await page.getByLabel('Home square feet').fill('1500')
await page.getByLabel('Rent', { exact: true }).fill('24000')
await page.getByRole('button', { name: 'Save home office' }).click()
await page.getByText('Home office saved.').waitFor()
const office = await page.locator('.office-summary').innerText()
check(office.includes('10.00%') && office.includes('$750.00') && office.includes('$2,400.00'), 'home office: 10%, simplified $750, regular $2,400')
await shot(page, 'records-office')
await app.close()
done(errors)
