// Phase 8: dated rates, invoice rate prefill, sales tax report for a quarter, recording a payment.
import { launch, createCompany, shot, check, done, post } from '../lib.mjs'

const { app, page, errors } = await launch({ fresh: true })
await createCompany(page)

await page.getByRole('button', { name: 'Sales tax', exact: true }).click()
await page.getByRole('heading', { name: 'Sales tax', level: 2 }).waitFor()
await page.locator('.sales-tax .tabs').getByRole('button', { name: 'Rates' }).click()
await page.getByLabel('Rate place').fill('San Diego')
await page.getByLabel('Rate percent').fill('7.75')
await page.getByLabel('Rate starts on').fill('2026-01-01')
await page.getByRole('button', { name: 'Add rate' }).click()
await page.getByText('Rate added.').waitFor()
await page.getByLabel('Rate percent').fill('8')
await page.getByLabel('Rate starts on').fill('2026-04-01')
await page.getByRole('button', { name: 'Add rate' }).click()
await page.getByText('Rate added.').waitFor()
check((await page.locator('.sales-tax table').innerText()).includes('7.75%'), 'rates listed')
await page.getByRole('button', { name: 'Close' }).click()

// Invoice picks up the rate in force on its date.
await page.getByRole('button', { name: 'Invoices', exact: true }).click()
await page.locator('.sales .tabs').getByRole('button', { name: /^Customers/ }).click()
await page.getByLabel('Customer name').fill('Pat Retail')
await page.getByRole('button', { name: 'Add customer' }).click()
await page.locator('.sales .tabs').getByRole('button', { name: 'Invoices', exact: true }).click()
await page.getByRole('button', { name: 'New invoice' }).click()
await page.getByLabel('Invoice customer').selectOption({ label: 'Pat Retail' })
await page.getByLabel('Invoice date').fill('2026-02-15')
await page.waitForFunction(() => document.querySelector('[aria-label="Sales tax rate"]')?.value === '7.75')
check(true, 'invoice in February starts at 7.75%')
await page.getByLabel('Invoice date').fill('2026-04-15')
await page.waitForFunction(() => document.querySelector('[aria-label="Sales tax rate"]')?.value === '8')
check(true, 'invoice in April starts at 8%')
await page.getByLabel('Invoice date').fill('2026-02-15')
await page.getByLabel('Due date').fill('2026-03-15')
await page.getByLabel('Line 1 description').fill('Custom ring')
await page.getByLabel('Line 1 price').fill('400')
await page.getByRole('button', { name: 'Finalize invoice' }).click()
await page.locator('.invoice-list').waitFor()
await page.getByRole('button', { name: 'Close' }).click()

// A craft-fair sale entered without tax (to show the difference line).
await post(page, '2026-03-10', 'Craft fair cash', [['1000', 5000], ['4000', -5000]])
await page.reload()
await page.waitForSelector('.app-main h1')

await page.getByRole('button', { name: 'Sales tax', exact: true }).click()
await page.getByLabel('Sales tax year').selectOption('2026')
await page.locator('.quarter-buttons').getByRole('button', { name: 'Q1' }).click()
await page.locator('.tax-report').waitFor()
const rep = await page.locator('.tax-report').innerText()
check(/Total sales[\s\S]*\$450\.00/.test(rep), 'total sales 450.00')
check(/Taxable sales\s*\$450\.00/.test(rep), 'taxable 450.00')
check(/Tax at the rates in force[\s\S]*\$34\.88/.test(rep), 'tax at 7.75% = 34.88')
check(/Sales tax you charged[^\n]*\n?[^\n]*\$31\.00/.test(rep), 'charged 31.00')
check(/Difference[\s\S]*\$3\.88/.test(rep), 'difference 3.88 flagged')
await shot(page, 'salestax-report')

await page.getByRole('button', { name: 'Record a sales tax payment…' }).click()
check((await page.getByLabel('Tax payment amount').inputValue()) === '31.00', 'payment defaults to what is owed')
await page.getByLabel('Tax payment date').fill('2026-04-28')
await page.getByRole('button', { name: 'Record payment' }).click()
await page.getByText(/Sales tax payment recorded/).waitFor()
await page.locator('.quarter-buttons').getByRole('button', { name: 'Q2' }).click()
await page.waitForFunction(() => document.querySelector('.tax-report')?.textContent?.includes('2026-06-30'))
const q2 = await page.locator('.tax-report').innerText()
check(/payments recorded in this period[\s\S]*\$31\.00/.test(q2), 'Q2 shows the payment')
check(/Sales tax payable on 2026-06-30\s*\$0\.00/.test(q2), 'nothing owed after paying')
await app.close()
done(errors)
