// 9d: sub-accounts on the chart and in the profit & loss.
import { launch, createCompany, shot, check, done, post } from '../lib.mjs'

const { app, page, errors } = await launch({ fresh: true })
await createCompany(page)
await page.getByRole('button', { name: 'Chart of accounts' }).click()
await page.getByRole('button', { name: 'Add account' }).click()
await page.getByLabel('Number').fill('6105')
await page.getByLabel('Name').fill('Show booth fees')
await page.getByLabel('Tax category').selectOption('commissions_fees')
await page.getByLabel('Sub-account of').selectOption({ label: '6100 Marketplace and payment fees' })
await page.getByRole('button', { name: 'Add account' }).last().click()
await page.locator('tr.sub-account').filter({ hasText: 'Show booth fees' }).waitFor()
const rows = await page.locator('.chart-table tbody tr').allInnerTexts()
const parentAt = rows.findIndex((r) => r.includes('Marketplace and payment fees'))
check(rows[parentAt + 1]?.includes('Show booth fees'), 'sub-account listed right under its parent')
await shot(page, 'subaccounts-chart')

await post(page, '2026-03-01', 'Booth', [['6105', 15000], ['1000', -15000]])
await post(page, '2026-03-02', 'Fees', [['6100', 2000], ['1000', -2000]])
await page.reload()
await page.waitForSelector('.app-main h1')
await page.getByRole('button', { name: 'Reports', exact: true }).click()
await page.getByLabel('Report from').fill('2026-01-01')
await page.getByLabel('Report to').fill('2026-12-31')
await page.locator('.report-table').waitFor()
const pl = await page.locator('.report-table').innerText()
check(/Total Marketplace and payment fees\s*\$170\.00/.test(pl), 'P&L subtotal for the parent (170.00)')
check(/Total expenses\s*\$170\.00/.test(pl), 'section total counts each account once')
await shot(page, 'subaccounts-pl')
await app.close()
done(errors)
