import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type { JunoApi } from './types'

const api: JunoApi = {
  getAppInfo: () => ipcRenderer.invoke('app:getInfo'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  chooseDataFolder: () => ipcRenderer.invoke('settings:chooseFolder'),
  useDataFolder: (dir) => ipcRenderer.invoke('settings:useFolder', dir),
  openDataFolder: () => ipcRenderer.invoke('settings:openFolder'),
  listCompanies: () => ipcRenderer.invoke('companies:list'),
  getCurrentCompany: () => ipcRenderer.invoke('companies:current'),
  openCompany: (folder) => ipcRenderer.invoke('companies:open', folder),
  createCompany: (input) => ipcRenderer.invoke('companies:create', input),
  getHistory: () => ipcRenderer.invoke('company:history'),
  changeEntityType: (input) => ipcRenderer.invoke('company:changeEntityType', input),
  correctStartingEntityType: (entityType) => ipcRenderer.invoke('company:correctStartingEntityType', entityType),
  removeEntityTypeChange: (effectiveDate) => ipcRenderer.invoke('company:removeEntityTypeChange', effectiveDate),
  changeHomeState: (input) => ipcRenderer.invoke('company:changeHomeState', input),
  correctStartingHomeState: (stateCode) => ipcRenderer.invoke('company:correctStartingHomeState', stateCode),
  removeHomeStateChange: (effectiveDate) => ipcRenderer.invoke('company:removeHomeStateChange', effectiveDate),
  restoreAccounts: (numbers) => ipcRenderer.invoke('accounts:restore', numbers),
  getChart: () =>ipcRenderer.invoke('chart:get'),
  setupChart: (template) => ipcRenderer.invoke('chart:setup', template),
  addAccount: (input) => ipcRenderer.invoke('accounts:add', input),
  updateAccount: (id, input) => ipcRenderer.invoke('accounts:update', id, input),
  setAccountActive: (id, active) => ipcRenderer.invoke('accounts:setActive', id, active),
  deleteAccount: (id) => ipcRenderer.invoke('accounts:delete', id),
  postManualEntry: (input) => ipcRenderer.invoke('entries:postManual', input),
  listEntries: () => ipcRenderer.invoke('entries:list'),
  getOpeningBalances: () => ipcRenderer.invoke('opening:get'),
  saveOpeningBalances: (input) => ipcRenderer.invoke('opening:save', input),
  listAttachments: (entryId) => ipcRenderer.invoke('attachments:list', entryId),
  addAttachments: (entryId, paths) => ipcRenderer.invoke('attachments:add', entryId, paths),
  pickAttachments: (entryId) => ipcRenderer.invoke('attachments:pick', entryId),
  openAttachment: (id) => ipcRenderer.invoke('attachments:open', id),
  showAttachment: (id) => ipcRenderer.invoke('attachments:show', id),
  removeAttachment: (id, reason) => ipcRenderer.invoke('attachments:remove', id, reason),
  pathForFile: (file) => webUtils.getPathForFile(file),
  pickImportFile: () => ipcRenderer.invoke('imports:pickFile'),
  readImportFile: (path) => ipcRenderer.invoke('imports:readFile', path),
  savedMapping: (accountId, text, hasHeader) => ipcRenderer.invoke('imports:savedMapping', accountId, text, hasHeader),
  stageImport: (input) => ipcRenderer.invoke('imports:stage', input),
  linesToReview: (accountId) => ipcRenderer.invoke('imports:review', accountId),
  ignoredLines: (accountId) => ipcRenderer.invoke('imports:ignored', accountId),
  reviewCounts: () => ipcRenderer.invoke('imports:counts'),
  postBankLines: (items) => ipcRenderer.invoke('imports:post', items),
  matchBankLine: (lineId, entryId) => ipcRenderer.invoke('imports:match', lineId, entryId),
  ignoreBankLines: (ids) => ipcRenderer.invoke('imports:ignore', ids),
  restoreBankLine: (id) => ipcRenderer.invoke('imports:restore', id),
  importHistory: () => ipcRenderer.invoke('imports:history'),
  listRules: () => ipcRenderer.invoke('rules:list'),
  addRule: (input) => ipcRenderer.invoke('rules:add', input),
  updateRule: (id, input) => ipcRenderer.invoke('rules:update', id, input),
  deleteRule: (id) => ipcRenderer.invoke('rules:delete', id),
  getReconcile: (accountId) => ipcRenderer.invoke('reconcile:get', accountId),
  setStatement: (accountId, date, cents) => ipcRenderer.invoke('reconcile:statement', accountId, date, cents),
  setCleared: (accountId, lineIds, cleared) => ipcRenderer.invoke('reconcile:clear', accountId, lineIds, cleared),
  finishReconciliation: (accountId) => ipcRenderer.invoke('reconcile:finish', accountId),
  cancelReconciliation: (accountId) => ipcRenderer.invoke('reconcile:cancel', accountId),
  undoReconciliation: (accountId, reason) => ipcRenderer.invoke('reconcile:undo', accountId, reason),
  getRegister: (q) => ipcRenderer.invoke('accounts:register', q),
  voidEntry: (id, reason) => ipcRenderer.invoke('entries:void', id, reason),
  reverseEntry: (id, date, memo) => ipcRenderer.invoke('entries:reverse', id, date, memo)
}

contextBridge.exposeInMainWorld('juno', api)
